-- =====================================================
-- V1__init_schema.sql
-- 初始化 schema（仅 M1-M6 文字面试核心）
-- 其它模块（知识库 / LLM Provider / RAG Chat / 语音面试 / 面试日程）
-- 在对应里程碑用单独迁移文件追加
-- =====================================================

-- 简历
CREATE TABLE resumes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  access_count INTEGER,
  analyze_error VARCHAR(500),
  analyze_status VARCHAR(20),
  content_type VARCHAR(255),
  file_hash VARCHAR(64) NOT NULL,
  file_size BIGINT,
  last_accessed_at TIMESTAMP(6),
  original_filename VARCHAR(255) NOT NULL,
  resume_text TEXT,
  storage_key VARCHAR(500),
  storage_url VARCHAR(1000),
  uploaded_at TIMESTAMP(6) NOT NULL,
  CONSTRAINT resumes_analyze_status_check
    CHECK (analyze_status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')),
  CONSTRAINT idx_resume_hash UNIQUE (file_hash)
);

-- 简历分析结果（六维度评分）
CREATE TABLE resume_analyses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  analyzed_at TIMESTAMP(6) NOT NULL,
  content_score INTEGER,
  expression_score INTEGER,
  overall_score INTEGER,
  project_score INTEGER,
  skill_match_score INTEGER,
  strengths_json TEXT,
  structure_score INTEGER,
  suggestions_json TEXT,
  summary TEXT,
  resume_id BIGINT NOT NULL,
  CONSTRAINT fkrp4f11h23bp0j118yan185lr5
    FOREIGN KEY (resume_id) REFERENCES resumes(id)
);

-- 面试会话（核心）
CREATE TABLE interview_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  completed_at TIMESTAMP(6),
  created_at TIMESTAMP(6) NOT NULL,
  current_question_index INTEGER,
  difficulty VARCHAR(16),
  evaluate_error VARCHAR(500),
  evaluate_status VARCHAR(20),
  improvements_json TEXT,
  interview_category VARCHAR(64),
  llm_provider VARCHAR(50),
  overall_feedback TEXT,
  overall_score INTEGER,
  questions_json TEXT,
  reference_answers_json TEXT,
  resume_id BIGINT,
  session_id VARCHAR(36) NOT NULL,
  skill_id VARCHAR(64),
  source_type VARCHAR(32),
  status VARCHAR(20),
  strengths_json TEXT,
  total_questions INTEGER,
  CONSTRAINT interview_sessions_evaluate_status_check
    CHECK (evaluate_status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')),
  CONSTRAINT interview_sessions_status_check
    CHECK (status IN ('CREATED', 'IN_PROGRESS', 'COMPLETED', 'EVALUATED')),
  CONSTRAINT uk42bhenf7mu90ochoc1efpg3xa UNIQUE (session_id),
  CONSTRAINT fkhresfe6p1s53klvmqhxxissa2
    FOREIGN KEY (resume_id) REFERENCES resumes(id)
);

-- 面试回答
CREATE TABLE interview_answers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  answered_at TIMESTAMP(6) NOT NULL,
  category VARCHAR(255),
  feedback TEXT,
  key_points_json TEXT,
  question TEXT,
  question_index INTEGER,
  reference_answer TEXT,
  score INTEGER,
  user_answer TEXT,
  session_id BIGINT NOT NULL,
  CONSTRAINT uk_interview_answer_session_question UNIQUE (session_id, question_index),
  CONSTRAINT fkjeqvvamvdarrcbswn6kkiuym9
    FOREIGN KEY (session_id) REFERENCES interview_sessions(id)
);

-- 索引
CREATE INDEX idx_interview_answer_session_question
  ON interview_answers (session_id, question_index);
CREATE INDEX idx_interview_session_resume_created
  ON interview_sessions (resume_id, created_at);
CREATE INDEX idx_interview_session_resume_status_created
  ON interview_sessions (resume_id, status, created_at);
CREATE INDEX idx_interview_session_skill_created
  ON interview_sessions (skill_id, created_at);

COMMENT ON COLUMN interview_sessions.interview_category IS '知识库面试方向（普通面试为 NULL，后续 M7 接入知识库时使用）';
